In [1]:
import pandas as pd
import numpy as np
import os,sys
import re
pwd = os.getcwd()

In [3]:
# reading dataset
kb_df = pd.read_csv(pwd+"//kabitakitchen.csv",encoding_errors='ignore')
kb_df

,id,commentText,Labels
0,Ugy_CBm-_CKA3YqrzcB4AaABAg,Pudina ptta nhi dalu to,7
1,Ugy9mx9nuTWJu4dRac14AaABAg,Chiken kacha tu ni rhy ga sis,7
2,Ugz8T2MKLYucL3dM9nh4AaABAg,"Hello mam, I love your all recipes.... ðŸ˜‹ðŸ˜‹ðŸ˜‹\nAl...",4
3,Ugx_1cCjRbCaDgL0FLF4AaABAg,Its awesome recipe plzz make handi chicken in ...,2
4,UgzLhKVAJ6NN3nZXyjN4AaABAg,Yeh jo measurement hai.........kitne logon ke ...,7
...,...,...,...
4895,UgjFXyC0Qhzk5ngCoAEC,i love chole...thank you kabitaji for sharing ...,1
4896,UghP3bitlJuM13gCoAEC,thnakyou mm,1
4897,UghztLZOqvedfXgCoAEC,thanks mam,1
4898,UggX5Fi2Y430zXgCoAEC,u r fabulous,4
4899,UghTaB9XvOQ_MngCoAEC,thnq fr the recipe. ðŸ’œ,1

### Cleaning data

In [3]:
# replacing enter with ';'
kb_df['commentText'] = kb_df['commentText'].str.replace('\n',';')
kb_df

,id,commentText,Labels
0,Ugy_CBm-_CKA3YqrzcB4AaABAg,Pudina ptta nhi dalu to,7
1,Ugy9mx9nuTWJu4dRac14AaABAg,Chiken kacha tu ni rhy ga sis,7
2,Ugz8T2MKLYucL3dM9nh4AaABAg,"Hello mam, I love your all recipes.... ðŸ˜‹ðŸ˜‹ðŸ˜‹;All...",4
3,Ugx_1cCjRbCaDgL0FLF4AaABAg,Its awesome recipe plzz make handi chicken in ...,2
4,UgzLhKVAJ6NN3nZXyjN4AaABAg,Yeh jo measurement hai.........kitne logon ke ...,7
...,...,...,...
4895,UgjFXyC0Qhzk5ngCoAEC,i love chole...thank you kabitaji for sharing ...,1
4896,UghP3bitlJuM13gCoAEC,thnakyou mm,1
4897,UghztLZOqvedfXgCoAEC,thanks mam,1
4898,UggX5Fi2Y430zXgCoAEC,u r fabulous,4
4899,UghTaB9XvOQ_MngCoAEC,thnq fr the recipe. ðŸ’œ,1

In [4]:
# kb_df['only_words'] = kb_df['commentText'].apply(lambda x: re.findall(r'\w+',x))
# kb_df

In [5]:
# getting stop words
with open(pwd+'//hinglish_stopwords_filter.txt','r') as sw:
    stw_list = sw.readlines()
stw_l = list(map(lambda x: x.strip(),stw_list))

# Vectorizations

### TFIDF Vectorizer

In [6]:
from sklearn.feature_extraction.text import TfidfVectorizer
tvectorizer = TfidfVectorizer(lowercase=True,stop_words=stw_l,max_features = 500)
Z = tvectorizer.fit_transform(kb_df['commentText'])
word_vec_arr = Z.toarray()
word_vec_cols = tvectorizer.get_feature_names()

C:\Users\murth\anaconda3\lib\site-packages\sklearn\feature_extraction\text.py:388: UserWarning: Your stop_words may be inconsistent with your preprocessing. Tokenizing the stop words generated tokens ['don', 'mon'] not in stop_words.
  warnings.warn('Your stop_words may be inconsistent with '

In [7]:
tfidf_500_df = pd.DataFrame(word_vec_arr,columns=word_vec_cols)
tfidf_500_df

,10,1kg,aa,aacha,aapka,aapke,aapki,about,accha,acche,...,wow,yammi,yammy,yesterday,yr,yum,yumm,yummi,yummy,zam
0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4895,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4896,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4897,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4898,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4899,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [8]:
#tfidf_500_df.to_csv(pwd+'//tfidf_500_vectors.csv',index=False)

### Count Vectorizer

In [9]:
from sklearn.feature_extraction.text import CountVectorizer
cvectorizer = CountVectorizer(lowercase=True,stop_words=stw_l,max_features = 500)
X = cvectorizer.fit_transform(kb_df['commentText'])
cword_vec_cols = cvectorizer.get_feature_names()
cword_vec_arr = X.toarray()

C:\Users\murth\anaconda3\lib\site-packages\sklearn\feature_extraction\text.py:388: UserWarning: Your stop_words may be inconsistent with your preprocessing. Tokenizing the stop words generated tokens ['don', 'mon'] not in stop_words.
  warnings.warn('Your stop_words may be inconsistent with '

In [10]:
cv_500_df = pd.DataFrame(cword_vec_arr,columns=cword_vec_cols)
cv_500_df

,10,1kg,aa,aacha,aapka,aapke,aapki,about,accha,acche,...,wow,yammi,yammy,yesterday,yr,yum,yumm,yummi,yummy,zam
0,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
3,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4895,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4896,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4897,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4898,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4899,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [11]:
#cv_500_df.to_csv(pwd+'//cv_500_vectors.csv',index=False)

### Term Frequency Vectorizer

In [12]:
from sklearn.feature_extraction.text import TfidfVectorizer
tfvectorizer = TfidfVectorizer(lowercase=True,stop_words=stw_l,max_features = 500,use_idf=False)
tf = tfvectorizer.fit_transform(kb_df['commentText'])
tfword_vec_arr = tf.toarray()
tfword_vec_cols = tfvectorizer.get_feature_names()

C:\Users\murth\anaconda3\lib\site-packages\sklearn\feature_extraction\text.py:388: UserWarning: Your stop_words may be inconsistent with your preprocessing. Tokenizing the stop words generated tokens ['don', 'mon'] not in stop_words.
  warnings.warn('Your stop_words may be inconsistent with '

In [13]:
tf_500_df = pd.DataFrame(tfword_vec_arr,columns=tfword_vec_cols)
tf_500_df

,10,1kg,aa,aacha,aapka,aapke,aapki,about,accha,acche,...,wow,yammi,yammy,yesterday,yr,yum,yumm,yummi,yummy,zam
0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4895,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4896,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4897,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4898,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4899,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [14]:
#tf_500_df.to_csv(pwd+'//tf_500_vectors.csv',index=False)

# Modelling

In [2]:
# importing algorithms
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.neighbors import KNeighborsClassifier

### data split for TFIDF data

In [16]:
x_train,x_test,y_train,y_test = train_test_split(tfidf_500_df,kb_df['Labels'],test_size=0.30,
                                                 random_state=21,stratify=kb_df['Labels'])

### Logistic regression for TFIDF data

In [17]:
# applying logistic regression
tv_lr_model = LogisticRegression()
tv_lr_model.fit(x_train,y_train)
tv_lr_pred_val = tv_lr_model.predict(x_test)
tv_lr_model.score(x_test,y_test)

0.7517006802721088

In [18]:
tv_lr_dict = {}
for x in tv_lr_pred_val:
    try:
        tv_lr_dict[str(x)] += 1
    except:
        tv_lr_dict[str(x)] = 0
        tv_lr_dict[str(x)] += 1
        
tv_lr_dict

{'5': 164, '6': 251, '2': 191, '7': 215, '3': 225, '4': 235, '1': 189}

In [19]:
tv_lr_real_dict = {}
for x in y_test:
    try:
        tv_lr_real_dict[str(x)] += 1
    except:
        tv_lr_real_dict[str(x)] = 0
        tv_lr_real_dict[str(x)] += 1
        
tv_lr_real_dict

{'5': 210, '6': 210, '7': 210, '2': 210, '3': 210, '4': 210, '1': 210}

### KNN for TFIDF data

In [20]:
# applying KNN algorithm
# taking squareroot(n) as k value. as total rows are 4900, k-value = 70
tv_knn_model = KNeighborsClassifier(n_neighbors=70)
tv_knn_model.fit(x_train,y_train)
tv_knn_pred_val = tv_knn_model.predict(x_test)
tv_knn_model.score(x_test,y_test)

0.3598639455782313

In [21]:
# checking the accuracies of neighbors in [3, 4, 5, 6, 7, 8] for KNN
neighbors_list = [3, 4, 5, 6, 7, 8]
for x in neighbors_list:
    tv_knn_model = KNeighborsClassifier(n_neighbors=x)
    tv_knn_model.fit(x_train,y_train)
    print("Accuracy of KNN model for {} neighbors is:".format(str(x)), 
          tv_knn_model.score(x_test,y_test))

Accuracy of KNN model for 3 neighbors is: 0.5639455782312925
Accuracy of KNN model for 4 neighbors is: 0.5564625850340136
Accuracy of KNN model for 5 neighbors is: 0.5585034013605442
Accuracy of KNN model for 6 neighbors is: 0.5482993197278911
Accuracy of KNN model for 7 neighbors is: 0.5380952380952381
Accuracy of KNN model for 8 neighbors is: 0.535374149659864

### data split for Count vectorizer data

In [22]:
x_train,x_test,y_train,y_test = train_test_split(cv_500_df,kb_df['Labels'],test_size=0.30,
                                                 random_state=21,stratify=kb_df['Labels'])

### Logistic regression for Count vectorizer data

In [23]:
# applying logistic regression for cv vectorizer
cv_lr_model = LogisticRegression()
cv_lr_model.fit(x_train,y_train)
cv_lr_pred_val = cv_lr_model.predict(x_test)
cv_lr_model.score(x_test,y_test)

0.746938775510204

In [24]:
cv_lr_dict = {}
for x in cv_lr_pred_val:
    try:
        cv_lr_dict[str(x)] += 1
    except:
        cv_lr_dict[str(x)] = 0
        cv_lr_dict[str(x)] += 1
        
cv_lr_dict

{'5': 173, '6': 264, '2': 202, '7': 190, '3': 235, '4': 216, '1': 190}

### KNN for Count vectorizer data

In [25]:
# applying KNN algorithm
# taking squareroot(n) as k value. as total rows are 4900, k-value = 70
cv_knn_model = KNeighborsClassifier(n_neighbors=70)
cv_knn_model.fit(x_train,y_train)
cv_knn_pred_val = cv_knn_model.predict(x_test)
cv_knn_model.score(x_test,y_test)

0.4598639455782313

In [26]:
# checking the accuracies of neighbors in [3, 4, 5, 6, 7, 8] for KNN
neighbors_list = [3, 4, 5, 6, 7, 8]
for x in neighbors_list:
    cv_knn_model = KNeighborsClassifier(n_neighbors=x)
    cv_knn_model.fit(x_train,y_train)
    print("Accuracy of KNN model for {} neighbors is:".format(str(x)), 
          cv_knn_model.score(x_test,y_test))

Accuracy of KNN model for 3 neighbors is: 0.6040816326530613
Accuracy of KNN model for 4 neighbors is: 0.5857142857142857
Accuracy of KNN model for 5 neighbors is: 0.5850340136054422
Accuracy of KNN model for 6 neighbors is: 0.5795918367346938
Accuracy of KNN model for 7 neighbors is: 0.5748299319727891
Accuracy of KNN model for 8 neighbors is: 0.5761904761904761

### data split for Term frequency vectorizer data

In [27]:
x_train,x_test,y_train,y_test = train_test_split(tf_500_df,kb_df['Labels'],test_size=0.30,
                                                 random_state=21,stratify=kb_df['Labels'])

### Logistic regression for Term frequency vectorizer data

In [28]:
tf_lr_model = LogisticRegression()
tf_lr_model.fit(x_train,y_train)
tf_lr_pred_val = tf_lr_model.predict(x_test)
tf_lr_model.score(x_test,y_test)

0.7496598639455783

In [29]:
tf_lr_dict = {}
for x in tf_lr_pred_val:
    try:
        tf_lr_dict[str(x)] += 1
    except:
        tf_lr_dict[str(x)] = 0
        tf_lr_dict[str(x)] += 1
        
tf_lr_dict

{'5': 151, '6': 244, '2': 204, '7': 213, '3': 236, '4': 232, '1': 190}

In [30]:
tf_lr_real_dict = {}
for x in y_test:
    try:
        tf_lr_real_dict[str(x)] += 1
    except:
        tf_lr_real_dict[str(x)] = 0
        tf_lr_real_dict[str(x)] += 1
        
tf_lr_real_dict

{'5': 210, '6': 210, '7': 210, '2': 210, '3': 210, '4': 210, '1': 210}

### KNN for Term frequency vectorizer data

In [31]:
# applying KNN algorithm
# taking squareroot(n) as k value. as total rows are 4900, k-value = 70
tf_knn_model = KNeighborsClassifier(n_neighbors=70)
tf_knn_model.fit(x_train,y_train)
tf_knn_pred_val = tf_knn_model.predict(x_test)
tf_knn_model.score(x_test,y_test)

0.4217687074829932

In [32]:
# checking the accuracies of neighbors in [3, 4, 5, 6, 7, 8] for KNN
neighbors_list = [3, 4, 5, 6, 7, 8]
for x in neighbors_list:
    tf_knn_model = KNeighborsClassifier(n_neighbors=x)
    tf_knn_model.fit(x_train,y_train)
    print("Accuracy of KNN model for {} neighbors is:".format(str(x)), 
          tf_knn_model.score(x_test,y_test))

Accuracy of KNN model for 3 neighbors is: 0.6040816326530613
Accuracy of KNN model for 4 neighbors is: 0.5795918367346938
Accuracy of KNN model for 5 neighbors is: 0.580952380952381
Accuracy of KNN model for 6 neighbors is: 0.582312925170068
Accuracy of KNN model for 7 neighbors is: 0.5843537414965987
Accuracy of KNN model for 8 neighbors is: 0.5768707482993197

### Modelling on Transformers vectorized data

### BERT Dataset

In [3]:
# reading dataset
bert_df = pd.read_csv(pwd+"//bert_vectorized_kabita_dataset.csv")
bert_df

,0,1,2,3,4,5,6,7,8,9,...,758,759,760,761,762,763,764,765,766,767
0,0.099227,-0.182145,1.497459,0.065879,0.301111,0.512683,-0.520910,0.461645,0.303871,0.128705,...,0.360620,-0.674632,0.125654,0.133525,-0.180360,-0.291799,0.164079,-0.116920,-0.278621,0.563611
1,-0.379820,0.267697,1.343501,0.028609,0.229195,0.098835,-0.370463,0.476952,0.025788,0.348739,...,-0.180667,-1.320677,-0.059445,-0.180316,-0.255214,-0.780747,0.028456,-0.410423,0.083016,0.520066
2,-0.597901,0.700082,0.834766,0.191753,-0.451541,-1.084834,-0.306697,0.059381,0.553939,-0.511910,...,-1.321787,-1.658763,-0.707360,-1.926489,-0.616650,-0.670291,0.064648,-0.033047,0.130870,0.403199
3,-0.471285,-0.061829,-0.498971,-0.210086,0.714843,-0.274224,-1.213445,-0.127029,0.741553,-1.063075,...,-0.890410,-1.400618,-0.632397,-1.087415,-0.067796,0.286536,0.198744,-0.529115,0.331229,-0.240876
4,0.305518,0.333950,0.948599,-0.146274,0.520394,-0.067224,-0.516280,0.248486,0.119011,0.234385,...,0.058258,-1.033338,-0.036213,-0.068537,-0.141625,-0.331198,0.083700,-0.230058,-0.182552,0.441298
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4895,-0.500329,0.742406,0.716986,-0.512649,-0.389942,-0.650224,-0.517370,0.203030,0.153223,-0.627619,...,-0.888477,-1.651999,-1.086450,-1.524795,0.157590,-0.693399,-0.199692,0.404372,-0.103204,0.152734
4896,0.193286,0.189322,2.058987,0.721164,0.422046,0.399487,0.106806,0.945896,-0.292387,0.069524,...,0.045611,-0.377313,-0.147014,-0.252673,-0.476615,0.002734,0.257385,-0.206883,0.130351,0.450252
4897,0.067536,0.363559,2.493165,0.141181,0.250777,0.120106,-0.120063,0.887105,-0.160606,0.290866,...,-0.439551,-1.273829,0.359374,-1.228068,-0.148418,-0.569193,-0.353620,0.244859,-0.429521,0.458977
4898,0.161024,-0.015191,2.288679,0.334447,0.468611,-0.309379,0.055896,0.713560,0.173783,0.028278,...,-0.011762,-1.054880,0.602770,-1.066488,-0.248051,-0.251069,-0.431594,-0.518592,-0.022153,0.185179
4899,0.493920,0.266956,2.267644,0.201910,0.319839,-0.016935,0.395764,0.411011,0.382303,0.059625,...,-0.155305,-1.012162,-0.239928,-0.469554,-0.558377,-0.282658,0.328082,-0.546548,0.291623,0.733680

In [5]:
# Reading labels
labels_df = pd.read_csv(pwd+"//kabita_dataset_labels.csv")
labels_df

      kabita_labels
0                 7
1                 7
2                 4
3                 2
4                 7
...             ...
4895              1
4896              1
4897              1
4898              4
4899              1

[4900 rows x 1 columns]

In [5]:
x_train,x_test,y_train,y_test = train_test_split(bert_df,labels_df['kabita_labels'],test_size=0.30,
                                                 random_state=12,stratify=labels_df['kabita_labels'])

### KNN for Bert dataset

In [7]:
# checking the accuracies of neighbors in [3, 4, 5, 6, 7, 8] for KNN
neighbors_list = [3, 4, 5, 6, 7, 8]
for x in neighbors_list:
    bert_knn_model = KNeighborsClassifier(n_neighbors=x)
    bert_knn_model.fit(x_train,y_train)
    print("Accuracy of KNN model for {} neighbors is:".format(str(x)), 
          bert_knn_model.score(x_test,y_test))

Accuracy of KNN model for 3 neighbors is: 0.6755102040816326
Accuracy of KNN model for 4 neighbors is: 0.6965986394557823
Accuracy of KNN model for 5 neighbors is: 0.6904761904761905
Accuracy of KNN model for 6 neighbors is: 0.6918367346938775
Accuracy of KNN model for 7 neighbors is: 0.6959183673469388
Accuracy of KNN model for 8 neighbors is: 0.6850340136054421

In [8]:
# applying KNN algorithm
# taking squareroot(n) as k value. as total rows are 4900, k-value = 70
bert_knn_model = KNeighborsClassifier(n_neighbors=70)
bert_knn_model.fit(x_train,y_train)
bert_knn_pred_val = bert_knn_model.predict(x_test)
bert_knn_model.score(x_test,y_test)

0.6231292517006802

### Logistic for Bert dataset

In [9]:
bert_lr_model = LogisticRegression()
bert_lr_model.fit(x_train,y_train)
bert_lr_pred_val = bert_lr_model.predict(x_test)
bert_lr_model.score(x_test,y_test)

C:\Users\murth\anaconda3\lib\site-packages\sklearn\linear_model\_logistic.py:763: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(

0.7748299319727892

### GPT Dataset

In [10]:
# reading dataset
gpt_df = pd.read_csv(pwd+"//gpt_vectorized_kabita_dataset.csv")
gpt_df

,0,1,2,3,4,5,6,7,8,9,...,758,759,760,761,762,763,764,765,766,767
0,0.211974,1.270889,-0.175464,-0.056867,0.267969,1.777547,0.052245,1.326541,0.068738,-0.262352,...,0.336537,1.118200,0.008726,-0.328713,-0.092587,-0.201130,-0.181676,0.474237,0.311701,0.045535
1,-0.476183,0.516283,-0.316005,-0.168094,0.735854,0.865828,-0.611421,0.660393,-0.491673,0.045016,...,-0.121701,-0.316118,-0.496502,-0.762571,0.359269,-1.755350,-0.304121,-0.033146,0.449156,0.264330
2,0.544605,0.182465,0.465321,-1.052795,-0.554435,0.595691,0.380034,1.438977,-1.326972,-0.697750,...,-0.481327,-0.635220,-0.296181,-0.392727,0.117460,-0.589627,-1.169872,-0.109303,-0.465024,1.966946
3,0.386654,0.502101,0.522348,-1.459961,1.402257,-0.039568,0.060267,0.053887,-1.418120,0.159173,...,0.014832,-0.107940,0.057398,-0.887733,-0.549139,0.488153,-1.022718,-0.353387,-0.189969,0.616283
4,0.009521,0.193356,-0.527401,-0.329351,0.093132,-0.246717,-0.061068,0.575163,0.131107,0.450785,...,-0.202649,0.013554,-0.589659,-0.805061,1.253467,-0.462865,-0.152428,0.444929,0.587048,0.106981
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4895,0.340942,-0.222584,0.279221,-0.618760,1.340927,0.759075,0.068279,1.091592,0.165121,-0.055406,...,-0.528208,-0.385468,0.077745,-0.748396,-0.064917,-0.881079,-0.134982,0.552665,0.067825,1.186216
4896,-0.044812,0.050046,0.120236,-0.086727,0.232654,-0.033159,-0.593683,1.125542,0.106066,0.395994,...,0.183018,0.719590,-0.200128,-0.326415,0.513131,-1.007442,0.090349,0.518339,-0.087567,-0.622251
4897,-0.123655,0.354534,0.175377,-0.075972,0.438702,0.545708,-0.260574,-0.159305,0.232170,0.161077,...,-0.494661,0.415942,-0.382951,0.108540,0.158021,-0.191864,-0.330703,-0.407392,-0.315374,0.369046
4898,0.347110,0.643702,0.386423,-0.389618,1.385095,0.485864,0.034131,-0.572183,-0.455514,0.259953,...,0.192145,0.238542,0.584857,0.066534,0.168229,-1.100380,-1.170902,0.149117,-0.031141,0.276576
4899,-0.397129,0.096984,0.148870,-0.611734,0.368577,0.322632,-0.568928,0.012692,-0.406499,0.255511,...,-0.017053,0.647435,0.179804,-0.543546,0.548929,0.159491,-0.125520,0.352294,0.346845,0.179133

In [11]:
x_train,x_test,y_train,y_test = train_test_split(gpt_df,labels_df['kabita_labels'],test_size=0.30,
                                                 random_state=13,stratify=labels_df['kabita_labels'])

### KNN for GPT dataset

In [12]:
# checking the accuracies of neighbors in [3, 4, 5, 6, 7, 8] for KNN
neighbors_list = [3, 4, 5, 6, 7, 8]
for x in neighbors_list:
    gpt_knn_model = KNeighborsClassifier(n_neighbors=x)
    gpt_knn_model.fit(x_train,y_train)
    print("Accuracy of KNN model for {} neighbors is:".format(str(x)), 
          gpt_knn_model.score(x_test,y_test))

Accuracy of KNN model for 3 neighbors is: 0.6469387755102041
Accuracy of KNN model for 4 neighbors is: 0.6605442176870748
Accuracy of KNN model for 5 neighbors is: 0.6557823129251701
Accuracy of KNN model for 6 neighbors is: 0.6619047619047619
Accuracy of KNN model for 7 neighbors is: 0.6639455782312925
Accuracy of KNN model for 8 neighbors is: 0.6605442176870748

In [13]:
# applying KNN algorithm
# taking squareroot(n) as k value. as total rows are 4900, k-value = 70
gpt_knn_model = KNeighborsClassifier(n_neighbors=70)
gpt_knn_model.fit(x_train,y_train)
gpt_knn_pred_val = gpt_knn_model.predict(x_test)
gpt_knn_model.score(x_test,y_test)

0.6027210884353742

### Logistic for GPT dataset

In [14]:
gpt_lr_model = LogisticRegression()
gpt_lr_model.fit(x_train,y_train)
gpt_lr_pred_val = gpt_lr_model.predict(x_test)
gpt_lr_model.score(x_test,y_test)

C:\Users\murth\anaconda3\lib\site-packages\sklearn\linear_model\_logistic.py:763: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(

0.7537414965986394

### XLM Dataset

In [10]:
# reading dataset
xlm_df = pd.read_csv(pwd+"//xlm_vectorized_kabita_dataset.csv")
xlm_df

,0,1,2,3,4,5,6,7,8,9,...,758,759,760,761,762,763,764,765,766,767
0,0.151812,-0.104605,1.539529,0.029361,0.154102,0.133018,-0.005363,0.212237,0.024468,-0.198506,...,0.068829,-0.083013,0.362822,-0.117992,-0.306667,-0.253753,-0.062557,0.117001,-0.167814,0.127373
1,0.081537,0.098197,0.367645,-0.330848,-0.161488,-0.050640,0.541431,-0.194546,0.087313,0.291418,...,-0.177611,-0.708460,0.012157,0.081659,-0.331687,-0.853407,0.223658,-0.340625,0.229317,0.184941
2,-0.550148,0.656876,0.588075,-0.076227,-0.419885,-1.076565,-0.218123,-0.570240,0.483612,-0.343631,...,-1.489490,-1.186846,-0.807907,-1.735494,-0.937437,-0.345188,0.333478,-0.155762,-0.213616,0.370757
3,-0.006120,0.300767,-0.752691,0.072290,0.568322,-0.588587,-1.239129,-0.016606,0.289294,-0.919488,...,-0.805284,0.079214,-0.152704,-0.655298,-0.292821,0.758814,-0.436354,-0.781434,0.053460,0.124124
4,0.631572,0.570630,0.764983,0.022926,0.111415,0.173583,0.889820,0.149575,-0.228385,-0.014118,...,0.165725,0.325969,0.189849,-0.015694,-0.099618,-0.098397,0.158491,0.089691,-0.307322,0.527786
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4895,0.026107,0.443512,0.204197,-0.170294,-0.463828,-0.369364,0.405231,-0.261868,0.053398,-0.205520,...,-0.515016,-0.620114,-0.674546,-1.132345,0.049114,0.189943,-0.040248,0.757825,0.103981,-0.245268
4896,0.214164,0.328193,1.606320,0.228535,0.238380,0.008174,0.357487,0.510814,-0.354642,0.102032,...,0.166236,-0.017988,-0.164708,0.178974,0.125082,-0.111625,0.320988,-0.598676,0.275711,0.756566
4897,0.135810,0.314172,1.550947,-0.010735,-0.127331,-0.325620,0.490480,0.891232,-0.479866,0.436835,...,-1.126597,-0.588990,-0.195269,-1.218652,-0.418795,-0.167998,-0.239622,0.204943,-0.301166,0.603078
4898,-0.073194,0.240355,1.928025,0.197649,0.702981,-0.441209,-0.012740,0.799303,0.282713,-0.301204,...,-0.326109,-0.235134,0.451029,-0.436806,-0.187940,-0.355617,-0.249375,-0.543009,-0.135407,0.264905
4899,0.391781,0.460383,1.510468,-0.015880,0.359449,-0.553616,0.265187,0.108464,0.205196,-0.022984,...,-0.030076,-0.375827,0.195018,0.006165,-0.176790,0.118341,-0.058360,-0.778500,0.053842,0.791185

In [11]:
x_train,x_test,y_train,y_test = train_test_split(xlm_df,labels_df['kabita_labels'],test_size=0.30,
                                                 random_state=13,stratify=labels_df['kabita_labels'])

### KNN for XLM dataset

In [12]:
# checking the accuracies of neighbors in [3, 4, 5, 6, 7, 8] for KNN
neighbors_list = [3, 4, 5, 6, 7, 8]
for x in neighbors_list:
    xlm_knn_model = KNeighborsClassifier(n_neighbors=x)
    xlm_knn_model.fit(x_train,y_train)
    print("Accuracy of KNN model for {} neighbors is:".format(str(x)), 
          xlm_knn_model.score(x_test,y_test))

Accuracy of KNN model for 3 neighbors is: 0.6632653061224489
Accuracy of KNN model for 4 neighbors is: 0.6625850340136055
Accuracy of KNN model for 5 neighbors is: 0.6673469387755102
Accuracy of KNN model for 6 neighbors is: 0.6619047619047619
Accuracy of KNN model for 7 neighbors is: 0.6775510204081633
Accuracy of KNN model for 8 neighbors is: 0.6551020408163265

In [13]:
# applying KNN algorithm
# taking squareroot(n) as k value. as total rows are 4900, k-value = 70
xlm_knn_model = KNeighborsClassifier(n_neighbors=70)
xlm_knn_model.fit(x_train,y_train)
xlm_knn_pred_val = xlm_knn_model.predict(x_test)
xlm_knn_model.score(x_test,y_test)

0.6034013605442177

### Logistic for xlm dataset

In [14]:
xlm_lr_model = LogisticRegression()
xlm_lr_model.fit(x_train,y_train)
xlm_lr_pred_val = xlm_lr_model.predict(x_test)
xlm_lr_model.score(x_test,y_test)

C:\Users\murth\anaconda3\lib\site-packages\sklearn\linear_model\_logistic.py:763: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(

0.7551020408163265