In [1]:
import pandas as pd
import numpy as np
import os,sys
import re
pwd = os.getcwd()

In [2]:
# reading dataset
kb_df = pd.read_csv(pwd+"//kabitakitchen.csv")
kb_df

,id,commentText,Labels
0,Ugy_CBm-_CKA3YqrzcB4AaABAg,Pudina ptta nhi dalu to,7
1,Ugy9mx9nuTWJu4dRac14AaABAg,Chiken kacha tu ni rhy ga sis,7
2,Ugz8T2MKLYucL3dM9nh4AaABAg,"Hello mam, I love your all recipes.... ðŸ˜‹ðŸ˜‹ðŸ˜‹\nAl...",4
3,Ugx_1cCjRbCaDgL0FLF4AaABAg,Its awesome recipe plzz make handi chicken in ...,2
4,UgzLhKVAJ6NN3nZXyjN4AaABAg,Yeh jo measurement hai.........kitne logon ke ...,7
...,...,...,...
4895,UgjFXyC0Qhzk5ngCoAEC,i love chole...thank you kabitaji for sharing ...,1
4896,UghP3bitlJuM13gCoAEC,thnakyou mm,1
4897,UghztLZOqvedfXgCoAEC,thanks mam,1
4898,UggX5Fi2Y430zXgCoAEC,u r fabulous,4
4899,UghTaB9XvOQ_MngCoAEC,thnq fr the recipe. ðŸ’œ,1

### Cleaning data

In [3]:
# replacing enter with ';'
kb_df['commentText'] = kb_df['commentText'].str.replace('\n',';')
kb_df

,id,commentText,Labels
0,Ugy_CBm-_CKA3YqrzcB4AaABAg,Pudina ptta nhi dalu to,7
1,Ugy9mx9nuTWJu4dRac14AaABAg,Chiken kacha tu ni rhy ga sis,7
2,Ugz8T2MKLYucL3dM9nh4AaABAg,"Hello mam, I love your all recipes.... ðŸ˜‹ðŸ˜‹ðŸ˜‹;All...",4
3,Ugx_1cCjRbCaDgL0FLF4AaABAg,Its awesome recipe plzz make handi chicken in ...,2
4,UgzLhKVAJ6NN3nZXyjN4AaABAg,Yeh jo measurement hai.........kitne logon ke ...,7
...,...,...,...
4895,UgjFXyC0Qhzk5ngCoAEC,i love chole...thank you kabitaji for sharing ...,1
4896,UghP3bitlJuM13gCoAEC,thnakyou mm,1
4897,UghztLZOqvedfXgCoAEC,thanks mam,1
4898,UggX5Fi2Y430zXgCoAEC,u r fabulous,4
4899,UghTaB9XvOQ_MngCoAEC,thnq fr the recipe. ðŸ’œ,1

In [4]:
# kb_df['only_words'] = kb_df['commentText'].apply(lambda x: re.findall(r'\w+',x))
# kb_df

### TFIDF Vectorization

In [4]:
with open(pwd+'//hinglish_stopwords_filter.txt','r') as sw:
    stw_list = sw.readlines()
stw_l = list(map(lambda x: x.strip(),stw_list))

In [41]:
from sklearn.feature_extraction.text import TfidfVectorizer
vectorizer1 = TfidfVectorizer(lowercase=True,stop_words=stw_l,max_features = 40)
X = vectorizer1.fit_transform(kb_df['commentText'])
print(X.toarray())
print(vectorizer1.get_feature_names())

[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]
['awesome', 'biryani', 'chicken', 'chole', 'cook', 'cooker', 'cooking', 'delicious', 'didi', 'easy', 'great', 'ji', 'kabita', 'kavita', 'lot', 'love', 'ma', 'made', 'maggi', 'make', 'mam', 'masala', 'nice', 'plz', 'recipe', 'recipes', 'rice', 'sharing', 'simple', 'super', 'superb', 'taste', 'tasty', 'thanku', 'time', 'today', 'ur', 'video', 'wow', 'yummy']

In [42]:
kb_arr = X.toarray()
for y in range(0,5):
    for x in kb_arr[y]:
        if x > 0:
            print(x)
    print(len(kb_arr[y]))
    print("***********************")

40
***********************
40
***********************
0.6336594739037397
0.417169481341116
0.651494662272547
40
***********************
0.5472132396279631
0.49588490536312985
0.5661255080624246
0.36627549758335043
40
***********************
40
***********************

In [43]:
from sklearn.feature_extraction.text import TfidfVectorizer
vectorizer2 = TfidfVectorizer(lowercase=True,stop_words=stw_l,max_features = 100)
Y = vectorizer2.fit_transform(kb_df['commentText'])
print(Y.toarray())
print(vectorizer2.get_feature_names())

[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]
['aapki', 'achi', 'add', 'amazing', 'apki', 'awesome', 'bahot', 'bhot', 'bhut', 'biriyani', 'biryani', 'chef', 'chicken', 'chiken', 'chole', 'cook', 'cooked', 'cooker', 'cooking', 'cute', 'dear', 'delicious', 'didi', 'dish', 'don', 'dum', 'easy', 'explained', 'family', 'fan', 'follow', 'food', 'ghee', 'god', 'great', 'home', 'jal', 'ji', 'kabita', 'kabitaji', 'kavita', 'kg', 'kr', 'lot', 'love', 'loved', 'lovely', 'ma', 'maam', 'madam', 'made', 'maggi', 'maggie', 'make', 'making', 'mam', 'masala', 'mem', 'mene', 'ni', 'nice', 'oil', 'pan', 'pasand', 'plz', 'powder', 'pressure', 'recepie', 'recipe', 'recipes', 'reply', 'rice', 'shahi', 'sharing', 'simple', 'sister', 'skte', 'son', 'soo', 'step', 'style', 'super', 'superb', 'sweet', 'taste', 'tasty', 'testy', 'thanku', 'thankyou', 'time', 'today', 'turned', 'ur', 'video', 'videos', 'voice', 'water', 'wonderful', 'wow', 'yummy']

In [44]:
kb_arry = Y.toarray()
for y in range(0,5):
    for x in kb_arry[y]:
        if x > 0:
            print(x)
    print(len(kb_arry[y]))
    print("***********************")

100
***********************
0.6893845811004494
0.7243955406688791
100
***********************
0.6336594739037397
0.417169481341116
0.651494662272547
100
***********************
0.5472132396279631
0.49588490536312985
0.5661255080624246
0.36627549758335043
100
***********************
100
***********************

In [5]:
from sklearn.feature_extraction.text import TfidfVectorizer
vectorizer3 = TfidfVectorizer(lowercase=True,stop_words=stw_l,max_features = 500)
Z = vectorizer3.fit_transform(kb_df['commentText'])
word_vec_arr = Z.toarray()
word_vec_cols = vectorizer3.get_feature_names()

C:\Users\murth\anaconda3\lib\site-packages\sklearn\feature_extraction\text.py:388: UserWarning: Your stop_words may be inconsistent with your preprocessing. Tokenizing the stop words generated tokens ['don', 'mon'] not in stop_words.
  warnings.warn('Your stop_words may be inconsistent with '

In [6]:
tfidf_500_df = pd.DataFrame(word_vec_arr,columns=word_vec_cols)
tfidf_500_df

,10,1kg,aa,aacha,aapka,aapke,aapki,about,accha,acche,...,wow,yammi,yammy,yesterday,yr,yum,yumm,yummi,yummy,zam
0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4895,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4896,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4897,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4898,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4899,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [7]:
tfidf_500_df.to_csv(pwd+'//tfidf_500_vectors.csv',index=False)

In [8]:
kb_arrz = Z.toarray()
for y in range(0,5):
    for x in kb_arrz[y]:
        if x > 0:
            print(x)
    print(len(kb_arrz[y]))
    print("***********************")

0.7285750902830005
0.6849659391671369
500
***********************
0.3957264684675857
0.44817606706839525
0.5031857936324479
0.4158237607011312
0.46522406664330057
500
***********************
0.4221809948939447
0.41658817615899624
0.42836356916990037
0.24133395574365063
0.32214606590510914
0.37591417317766423
0.254562802189127
0.16759132709520827
0.2617278107082362
500
***********************
0.41871426152884483
0.37943906856783904
0.4331854693467599
0.6438215452407746
0.28026510212178296
500
***********************
1.0
500
***********************

In [11]:
from sklearn.feature_extraction.text import CountVectorizer
cvectorizer = CountVectorizer(lowercase=True,stop_words=stw_l,max_features = 500)
X = cvectorizer.fit_transform(kb_df['commentText'])
cword_vec_cols = cvectorizer.get_feature_names()
cword_vec_arr = X.toarray()

C:\Users\murth\anaconda3\lib\site-packages\sklearn\feature_extraction\text.py:388: UserWarning: Your stop_words may be inconsistent with your preprocessing. Tokenizing the stop words generated tokens ['don', 'mon'] not in stop_words.
  warnings.warn('Your stop_words may be inconsistent with '

In [12]:
cv_500_df = pd.DataFrame(cword_vec_arr,columns=cword_vec_cols)
cv_500_df

,10,1kg,aa,aacha,aapka,aapke,aapki,about,accha,acche,...,wow,yammi,yammy,yesterday,yr,yum,yumm,yummi,yummy,zam
0,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
3,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4895,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4896,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4897,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4898,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4899,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [13]:
cv_500_df.to_csv(pwd+'//cv_500_vectors.csv',index=False)